apiVersion: v1
kind: Service
metadata:
  labels:
    app: mssql
    tier: backend
  name: mssql-svc
spec:
  ports:
  - port: 1433
    protocol: TCP
    targetPort: 1433
  selector:
    app: mssql
    tier: backend
  type: ClusterIP